version: "3.9"

services:
  app:
    build: ./app
    container_name: php_app
    env_file: app.env
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/var/www/html

  db:
    image: postgres:13
    container_name: postgres_db
    env_file: db.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
