name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image (production)
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      - name: Push image (production)
        run: docker push ${{ secrets.DOCKER_REPO }}:latest
